version: "3.9"
services:
  apigateway:
    build:
      context: .
      dockerfile: apps/apigateway/Dockerfile
    ports:
      - "3003:3003"

  fitai:
    build:
      context: .
      dockerfile: apps/fitai/Dockerfile
    ports:
      - "5003:5003"
