export enum Tokens {
    ACCESS_TOKEN = 'ACCESS_TOKEN',
    REFRESH_TOKEN = 'REFRESH_TOKEN',
    RESET_PASSWORD_TOKEN = 'RESET_PASSWORD_TOKEN',
    EMAIL_VERIFICATION_TOKEN = 'EMAIL_VERIFICATION_TOKEN'
}